### ISSUE TITLE
Execute OpenRewrite from Catalog

### ISSUE THREAD

**Issue by fabapp2** [spring-projects/spring-cli#160]
Spike on a solution that allows users to execute recipes by name.
A new "Recipe Catalog" has mappings from the Recipe name to the recipe's artifact.
The Recipe Catalog also provides information about required and optional Recipe parameters.

_Recipe Catalog_
````yaml
recipeCatalog:
  - recipeId: AddLicenseHeader
    artifactGav: org.openrewrite:rewrite-java:8.13.4
    recipeName: org.openrewrite.java.AddLicenseHeader
    description: Adds the provided licenseText as license header to all Java files.
    repositoryUrl: https://github.com/openrewrite/rewrite
    parameters:
      - name: licenseText
        type: String
        required: true
````

## Providing Recipe Parameters
The mapping from command line arguments to Recipe parameters becomes quickly very complex.
For simple recipes with just String parameters like `AddLicenseHeader` that's not an issue.
But for more complex parameters, I'd change the API to expect parameters to be provided as JSON?

````shell
recipe byName <recipe-name> --parameters="{\"stringProperty\"=\"some string\", \"aList\"=[\"of\", \"strings\"]}"
````
